### ISSUE TITLE
 Guice provision errors

### ISSUE THREAD

**Issue by Kritiii** [feribg/audiogetter#1]
i compiled and run the app but when i search for any song it got crashed and show logcat error as:
FATAL EXCEPTION: main
Process: com.github.feribg.audiogetter, PID: 14007
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.Exception: The output folder: /storage/emulated/0/Music/samples is not writable
   at com.github.feribg.audiogetter.controllers.SourceController.<init>(Unknown Source)
   at com.github.feribg.audiogetter.controllers.SourceController.class(Unknown Source)
 while locating com.github.feribg.audiogetter.controllers.SourceController
   for field at com.github.feribg.audiogetter.ui.fragments.SearchResultsBaseFragment.sourceController(Unknown Source)
 while locating com.github.feribg.audiogetter.ui.fragments.SoundcloudSearchResultsFragment

1 error
   at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:451)
   at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:65)
   at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:944)
   at roboguice.inject.ContextScopedRoboInjector.injectMembersWithoutViews(ContextScopedRoboInjector.java:243)
   at roboguice.fragment.RoboListFragment.onCreate(RoboListFragment.java:13)
   at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
   at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:838)
   at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:861)
   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:719)
   at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
   at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
   at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
   at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
   at android.view.View.measure(View.java:17547)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
   at android.view.View.measure(View.java:17547)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
   at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:447)
   at android.view.View.measure(View.java:17547)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
   at android.view.View.measure(View.java:17547)
   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
   at android.view.Choreographer.doCallbacks(Choreographer.java:580)
   at android.view.Choreographer.doFrame(Choreographer.java:550)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5254)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.Exception: The output folder: /storage/emulated/0/Music/samples is not writable
at com.github.feribg.audiogetter.controllers.SourceController.<in

**Comment by feribg** [comment]
@Kritiii I'm really sorry but this project is not really supported or maintained.  It's state was very experimental, I would advice just copying the audio extraction code and rewriting the UI in modern Android. It seems that youtube is moving away from mp4 these days too, so even that part might not be super useful.

**Comment by MGlolenstine** [comment]
@Kritiii I'm really sorry for necro-bumping, but I've just come across this project and I wanted to at least help close this only issue.

Your problem is that you don't allow android permission to write external storage, that's why you got that error. This app might've worked for older android versions, but it most likely doesn't for new ones, as the permissions are a lot more strict than they used to be.

**Comment by feribg** [comment]
@MGlolenstine Happy to accept a PR if you want to help get it into a working state. Likely a lot of other parts are also geared towards android 4 or so

**Comment by YeMyoAung** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - NFT Holders
  - Participants in the Altlayer Campaign
  - EigenLayer Restakers
  - Partners in the EigenLayer Ecosystem
  - Celestia Stakers and more
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [here](https://go.altlayercommunity.online/XY2wna).

The window to [claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

huner1987, @WaterMr, @filipeoliveiraa, @davydovpv, @WBHGw, @BrummieDev, @eprofservices, @krazylek, @briwilcox, @Jonarod, @lianghappy, @wangyingjie110, @Calimos, @0xymor0n, @Luqis, @viserin, @algotradingadv, @jaycvilla, @GryphonR, @VallarasuS
